### ISSUE TITLE
Outlook 2000/2003 Retina Background Not Working

### ISSUE THREAD

**Issue by thomasaustin** [ThemeMountain/acorn#1]
Versions 2000, 2002, 2003 of Outlook don't seem to be scaling the background image to half the width.

**Comment by cossssmin** [comment]
Hi Thomas,

Retina background works fine in Outlook 2003, I just re-tested to make sure. Acorn isn't tested with Outlook 2000/2002 though, so they're not listed in the [compatibility table](https://thememountain.github.io/acorn/getting-started/compatibility.html). There are no plans to support those clients.

Here's a quick render test, compared to how it looks like in Apple Mail for reference. I used a 1200x800 background image with the [default background image example](https://github.com/ThemeMountain/acorn/blob/master/examples/bkg-image.html), which is a 600x400 container. As you can see, the image fits as expected in Outlook 2003.

### Outlook 2003

![image](https://user-images.githubusercontent.com/1656595/36944782-aaaedcb0-1fab-11e8-95f8-d92cf0f3df09.png)

### Apple Mail

![image](https://user-images.githubusercontent.com/1656595/36944787-be8b5efc-1fab-11e8-8c06-3e9beb04fe19.png)

### Code used

I only changed the image source in the default example:

```html
<table cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td class="col px-sm-16" bgcolor="#1F2225" background="https://picsum.photos/1200/800?image=1033" style="background-image: url('https://picsum.photos/1200/800?image=1033'); background-repeat: no-repeat; background-position: center; background-size: cover;" width="100%">
      <!--[if gte mso 9]>
      <v:image src="https://picsum.photos/1200/800?image=1033" xmlns:v="urn:schemas-microsoft-com:vml" style="width:600px;height:400px;" />
      <v:rect fill="false" stroke="false" style="position:absolute;width:600px;height:400px;">
      <div><![endif]-->
      <div class="spacer" style="line-height: 160px;">&zwnj;</div>
      <h1 style="color: #FFFFFF; font-size: 42px; font-weight: 300; line-height: 45px; margin: 0 0 10px; text-align: center;">Overlayed Text</h1>
      <div style="color: #FFFFFF; text-align: center;">CAN BE ANY HTML YOU NEED</div>
      <div class="spacer" style="line-height: 160px;">&zwnj;</div>
      <!--[if gte mso 9]></div></v:rect><![endif]-->
    </td>
  </tr>
</table>
```
